"use server";

import { revalidatePath, updateTag } from "next/cache";
import { cookies } from "next/headers";
import { createClient } from "@/utils/supabase/server";
import { createAdminClient } from "@/utils/supabase/admin";
import { CACHE_TAGS } from "@/lib/cache-tags";
import { logLeadActivity } from "@/lib/lead-activity-logger";
import type {
  ActionResult,
  Lead,
  LeadComment,
  LeadPayment,
  LeadCallLog,
  LeadFollowUp,
  CreateLeadInput,
  UpdateLeadInput,
} from "@/lib/types";

// ─────────────────────────────────────────────────────────────────────────────
// Shared client helper — avoids repeating cookie boilerplate in every action.
// Uses the user-scoped (RLS-respecting) Supabase client for all mutations.
// ─────────────────────────────────────────────────────────────────────────────
async function getUserClient() {
  const cookieStore = await cookies();
  return createClient(cookieStore);
}

/**
 * Creates a new lead record. The CID (Customer ID) is auto-generated by the
 * DB trigger `trigger_generate_lead_cid` based on source + date.
 *
 * @param input - Lead creation data. Uses `CreateLeadInput` to prevent passing
 *                join relations (sales_executive, cre, etc.) that exist only
 *                on the TypeScript type, not as DB columns.
 */
export async function createLead(
  input: CreateLeadInput
): Promise<ActionResult<Lead>> {
  const supabase = await getUserClient();

  const { data: { user } } = await supabase.auth.getUser();

  const { data, error } = await supabase
    .from("leads")
    .insert([input])
    .select()
    .single();

  if (error) return { success: false, error: error.message };

  updateTag(CACHE_TAGS.LEADS);
  updateTag(CACHE_TAGS.LEAD_STATUS_COUNTS);
  revalidatePath("/leads");

  // Fire-and-forget: log the creation
  logLeadActivity({
    leadId: data.id,
    actorId: user?.id,
    action: "lead.created",
    metadata: { source: input.source, name: input.name },
  });

  return { success: true, data: data as Lead };
}

/**
 * Updates specific fields on a lead. Uses `UpdateLeadInput` (not `Partial<Lead>`)
 * to ensure only real DB columns are sent — prevents accidental submission of
 * joined relation objects like `sales_executive` or `comments`.
 *
 * Automatically detects and logs the most meaningful change:
 *   status change → "lead.status_changed"
 *   cre_id change → "lead.assigned.cre"
 *   sales_executive_id change → "lead.assigned.sales"
 *   anything else → no activity log (minor field edits)
 *
 * @param id - Lead UUID
 * @param input - Only the fields to update
 */
export async function updateLead(
  id: string,
  input: UpdateLeadInput
): Promise<ActionResult<Lead>> {
  const supabase = await getUserClient();

  // Fetch current values BEFORE update for meaningful diff in logs
  // Only fetch if we're changing a tracked field (status, assignments)
  const isTrackedChange = "status" in input || "cre_id" in input || "sales_executive_id" in input;
  let prevData: Partial<Lead> = {};
  if (isTrackedChange) {
    const { data: prev } = await supabase
      .from("leads")
      .select("status, cre_id, sales_executive_id")
      .eq("id", id)
      .single();
    prevData = prev ?? {};
  }

  const { data: { user } } = await supabase.auth.getUser();

  const { data, error } = await supabase
    .from("leads")
    .update(input)
    .eq("id", id)
    .select()
    .single();

  if (error) return { success: false, error: error.message };

  updateTag(CACHE_TAGS.LEADS);
  updateTag(CACHE_TAGS.LEAD_DETAILS(id));
  updateTag(CACHE_TAGS.LEAD_STATUS_COUNTS);
  revalidatePath("/leads");
  revalidatePath(`/leads/${id}`);

  // Fire-and-forget activity logs (one per tracked change)
  if ("status" in input && input.status !== prevData.status) {
    logLeadActivity({
      leadId: id,
      actorId: user?.id,
      action: "lead.status_changed",
      metadata: { from: prevData.status, to: input.status },
    });
  }
  if ("cre_id" in input && input.cre_id !== prevData.cre_id) {
    logLeadActivity({
      leadId: id,
      actorId: user?.id,
      action: "lead.assigned.cre",
      metadata: { from: prevData.cre_id, to: input.cre_id },
    });
  }
  if (
    "sales_executive_id" in input &&
    input.sales_executive_id !== prevData.sales_executive_id
  ) {
    logLeadActivity({
      leadId: id,
      actorId: user?.id,
      action: "lead.assigned.sales",
      metadata: {
        from: prevData.sales_executive_id,
        to: input.sales_executive_id,
      },
    });
  }

  return { success: true, data: data as Lead };
}

/**
 * Adds a phone number to a lead's `phones` array.
 * Checks for duplicates before inserting to prevent data inconsistency.
 *
 * @param leadId - Lead UUID
 * @param phone - Phone number string to add
 */
export async function addLeadPhone(
  leadId: string,
  phone: string
): Promise<ActionResult<Lead>> {
  const supabase = await getUserClient();

  const { data: lead } = await supabase
    .from("leads")
    .select("phones")
    .eq("id", leadId)
    .single();

  const currentPhones = lead?.phones || [];
  if (currentPhones.includes(phone)) {
    return { success: false, error: "Phone number already exists" };
  }

  const { data: { user } } = await supabase.auth.getUser();

  const { data, error } = await supabase
    .from("leads")
    .update({ phones: [...currentPhones, phone] })
    .eq("id", leadId)
    .select()
    .single();

  if (error) return { success: false, error: error.message };

  updateTag(CACHE_TAGS.LEAD_DETAILS(leadId));
  revalidatePath(`/leads/${leadId}`);

  logLeadActivity({
    leadId,
    actorId: user?.id,
    action: "lead.phone_added",
    metadata: { phone },
  });

  return { success: true, data: data as Lead };
}

/**
 * Bulk-assigns one or more leads to a CRE or Sales Executive.
 * Used from the lead table's multi-select action bar.
 *
 * @param leadIds - Array of lead UUIDs to update
 * @param userId - Target user's UUID
 * @param type - Whether to assign as 'cre' or 'sales' executive
 */
export async function bulkAssignLeads(
  leadIds: string[],
  userId: string
): Promise<ActionResult<boolean>> {
  const supabase = await getUserClient();
  const adminClient = createAdminClient();

  const { data: { user } } = await supabase.auth.getUser();

  // Resolve the target user's department so current_department_id stays in sync
  const { data: targetUser } = await adminClient
    .from("users")
    .select("department_id")
    .eq("id", userId)
    .single();

  const { error } = await supabase
    .from("leads")
    .update({
      current_owner_id: userId,
      current_department_id: targetUser?.department_id ?? null,
    })
    .in("id", leadIds);

  if (error) return { success: false, error: error.message };

  updateTag(CACHE_TAGS.LEADS);
  leadIds.forEach((id) => updateTag(CACHE_TAGS.LEAD_DETAILS(id)));
  revalidatePath("/leads");

  // One log entry per lead (fire-and-forget, all non-blocking)
  for (const leadId of leadIds) {
    logLeadActivity({
      leadId,
      actorId: user?.id,
      action: "lead.assigned.bulk",
      metadata: { assignedUserId: userId, totalInBatch: leadIds.length },
    });
  }

  return { success: true, data: true };
}

/**
 * Adds a comment (optionally with image attachments) to a lead's activity feed.
 * The `comment_by` field is automatically set from the authenticated session.
 *
 * @param leadId - Lead UUID
 * @param comment - Comment text content
 * @param images - Optional array of Supabase storage public URLs
 */
export async function addLeadComment(
  leadId: string,
  comment: string,
  images: string[] = []
): Promise<ActionResult<LeadComment>> {
  const supabase = await getUserClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return { success: false, error: "Not authenticated" };

  const { data, error } = await supabase
    .from("lead_comments")
    .insert([
      {
        lead_id: leadId,
        comment_by: user.id,
        comment,
        images,
      },
    ])
    .select("*, user:users(id, name, profile_picture)")
    .single();

  if (error) return { success: false, error: error.message };

  updateTag(CACHE_TAGS.LEAD_DETAILS(leadId));
  revalidatePath(`/leads/${leadId}`);

  logLeadActivity({
    leadId,
    actorId: user.id,
    action: "lead.comment_added",
    metadata: { hasImages: images.length > 0, imageCount: images.length },
  });

  return { success: true, data: data as LeadComment };
}

/**
 * Records a payment against a lead. The `recorded_by` field is automatically
 * set from the authenticated session.
 *
 * Side-effect: After inserting, the computed finance view (`lead_finance_computed`)
 * will automatically reflect updated `totalPayment` and `totalDue` on next fetch —
 * no need to manually update the `finance` JSONB field.
 *
 * @param input - Payment data. `lead_id` is required.
 */
export async function addPayment(
  input: Partial<LeadPayment>
): Promise<ActionResult<LeadPayment>> {
  const supabase = await getUserClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();
  const paymentInput = { ...input, recorded_by: user?.id };

  const { data, error } = await supabase
    .from("lead_payments")
    .insert([paymentInput])
    .select("*, user:users(id, name, profile_picture)")
    .single();

  if (error) return { success: false, error: error.message };

  updateTag(CACHE_TAGS.LEAD_DETAILS(input.lead_id || ""));
  revalidatePath(`/leads/${input.lead_id}`);

  logLeadActivity({
    leadId: input.lead_id!,
    actorId: user?.id,
    action: "lead.payment_recorded",
    metadata: {
      amount: input.amount,
      method: input.payment_method,
      status: input.payment_status,
    },
  });

  return { success: true, data: data as LeadPayment };
}

/**
 * Records an outgoing/incoming call against a lead.
 * The `recorded_by` field is auto-set from the authenticated session.
 *
 * @param input - Call log data. `lead_id` is required.
 */
export async function addCallLog(
  input: Partial<LeadCallLog>
): Promise<ActionResult<LeadCallLog>> {
  const supabase = await getUserClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();
  const logInput = { ...input, recorded_by: user?.id };

  const { data, error } = await supabase
    .from("lead_call_logs")
    .insert([logInput])
    .select("*, user:users(id, name, profile_picture)")
    .single();

  if (error) return { success: false, error: error.message };

  updateTag(CACHE_TAGS.LEAD_DETAILS(input.lead_id || ""));
  revalidatePath(`/leads/${input.lead_id}`);

  logLeadActivity({
    leadId: input.lead_id!,
    actorId: user?.id,
    action: "lead.call_logged",
    metadata: {
      callType: input.call_type,
      status: input.status,
      recipient: input.recipient_number,
    },
  });

  return { success: true, data: data as LeadCallLog };
}

/**
 * Updates the project status (pipeline stage) of a lead and logs a comment.
 * Setting `status: "Ongoing"` is the convention for project-phase updates.
 *
 * @param leadId - Lead UUID
 * @param status - High-level project status (e.g., "Measuring", "Production")
 * @param subStatus - Finer-grained sub-status (e.g., "Material Ordered")
 * @param comment - Required progress note for the lead activity feed
 */
export async function updateLeadProjectStatus(
  leadId: string,
  status: string,
  subStatus: string,
  comment: string
): Promise<ActionResult<boolean>> {
  const supabase = await getUserClient();

  const { data: { user } } = await supabase.auth.getUser();

  // Fetch current project status (for diff log) + resolve "Ongoing" pipeline
  // status so the DB history trigger fires when current_status_id changes.
  const [{ data: prev }, { data: ongoingStatus }] = await Promise.all([
    supabase.from("leads").select("project_status").eq("id", leadId).single(),
    adminClient.from("pipeline_statuses").select("id, stage_id").eq("name", "Ongoing").single(),
  ]);

  const { error } = await supabase
    .from("leads")
    .update({
      status: "Ongoing",
      project_status: { status, subStatus },
      current_status_id: ongoingStatus?.id ?? null,
      current_stage_id: ongoingStatus?.stage_id ?? null,
    })
    .eq("id", leadId);

  if (error) return { success: false, error: error.message };

  await addLeadComment(leadId, comment);

  updateTag(CACHE_TAGS.LEAD_DETAILS(leadId));
  updateTag(CACHE_TAGS.LEADS);
  updateTag(CACHE_TAGS.LEAD_STATUS_COUNTS);
  revalidatePath(`/leads/${leadId}`);

  logLeadActivity({
    leadId,
    actorId: user?.id,
    action: "lead.project_status_changed",
    metadata: {
      from: prev?.project_status,
      to: { status, subStatus },
    },
  });

  return { success: true, data: true };
}

/**
 * Bulk-creates multiple lead records in a single transaction.
 *
 * @param leads - Array of lead creation inputs
 */
export async function createLeadsBulk(
  leads: CreateLeadInput[]
): Promise<ActionResult<{ inserted: number; failed: number }>> {
  if (!leads.length) return { success: false, error: "No leads to import" };

  const supabase = await getUserClient();

  const { data: { user } } = await supabase.auth.getUser();

  const { data, error } = await supabase
    .from("leads")
    .insert(leads)
    .select("id");

  if (error) return { success: false, error: error.message };

  updateTag(CACHE_TAGS.LEADS);
  updateTag(CACHE_TAGS.LEAD_STATUS_COUNTS);
  revalidatePath("/leads");

  // Log one entry per created lead (fire-and-forget)
  for (const row of data ?? []) {
    logLeadActivity({
      leadId: row.id,
      actorId: user?.id,
      action: "lead.created",
      metadata: { importedInBulk: true },
    });
  }

  return {
    success: true,
    data: {
      inserted: data?.length || 0,
      failed: leads.length - (data?.length || 0),
    },
  };
}

/**
 * Updates the status of a follow-up task.
 *
 * @param id - Follow-up UUID
 * @param status - New status (e.g., 'Complete', 'Pending')
 * @param leadId - Lead UUID for cache revalidation
 */
export async function updateFollowUpStatus(
  id: string,
  status: string,
  leadId: string
): Promise<ActionResult<boolean>> {
  const supabase = await getUserClient();

  const { data: { user } } = await supabase.auth.getUser();

  const { error } = await supabase
    .from("lead_follow_ups")
    .update({ status })
    .eq("id", id);

  if (error) return { success: false, error: error.message };

  updateTag(CACHE_TAGS.LEAD_DETAILS(leadId));
  revalidatePath(`/leads/${leadId}`);

  logLeadActivity({
    leadId,
    actorId: user?.id,
    action: "lead.follow_up_updated",
    metadata: { followUpId: id, newStatus: status },
  });

  return { success: true, data: true };
}

/**
 * Creates a new follow-up task for a lead.
 *
 * @param input - Follow-up data
 */
export async function createFollowUp(
  input: Partial<LeadFollowUp>
): Promise<ActionResult<LeadFollowUp>> {
  const supabase = await getUserClient();

  const { data: { user } } = await supabase.auth.getUser();

  const { data, error } = await supabase
    .from("lead_follow_ups")
    .insert([input])
    .select()
    .single();

  if (error) return { success: false, error: error.message };

  updateTag(CACHE_TAGS.LEAD_DETAILS(input.lead_id || ""));
  revalidatePath(`/leads/${input.lead_id}`);

  logLeadActivity({
    leadId: input.lead_id!,
    actorId: user?.id,
    action: "lead.follow_up_created",
    metadata: { type: input.type, scheduledAt: input.time, assignedTo: input.assigned_to },
  });

  return { success: true, data: data as LeadFollowUp };
}
