"use server";

import { revalidatePath, updateTag } from "next/cache";
import { cookies } from "next/headers";
import { createClient } from "@/utils/supabase/server";
import { CACHE_TAGS } from "@/lib/cache-tags";
import type {
  ActionResult,
  Lead,
  LeadComment,
  LeadPayment,
  LeadCallLog,
  LeadFollowUp,
  CreateLeadInput,
  UpdateLeadInput,
} from "@/lib/types";

// ─────────────────────────────────────────────────────────────────────────────
// Shared client helper — avoids repeating cookie boilerplate in every action.
// Uses the user-scoped (RLS-respecting) Supabase client for all mutations.
// ─────────────────────────────────────────────────────────────────────────────
async function getUserClient() {
  const cookieStore = await cookies();
  return createClient(cookieStore);
}

/**
 * Creates a new lead record. The CID (Customer ID) is auto-generated by the
 * DB trigger `trigger_generate_lead_cid` based on source + date.
 *
 * @param input - Lead creation data. Uses `CreateLeadInput` to prevent passing
 *                join relations (sales_executive, cre, etc.) that exist only
 *                on the TypeScript type, not as DB columns.
 */
export async function createLead(
  input: CreateLeadInput
): Promise<ActionResult<Lead>> {
  const supabase = await getUserClient();

  const { data, error } = await supabase
    .from("leads")
    .insert([input])
    .select()
    .single();

  if (error) return { success: false, error: error.message };

  updateTag(CACHE_TAGS.LEADS);
  updateTag(CACHE_TAGS.LEAD_STATUS_COUNTS);
  revalidatePath("/leads");

  return { success: true, data: data as Lead };
}

/**
 * Updates specific fields on a lead. Uses `UpdateLeadInput` (not `Partial<Lead>`)
 * to ensure only real DB columns are sent — prevents accidental submission of
 * joined relation objects like `sales_executive` or `comments`.
 *
 * @param id - Lead UUID
 * @param input - Only the fields to update
 */
export async function updateLead(
  id: string,
  input: UpdateLeadInput
): Promise<ActionResult<Lead>> {
  const supabase = await getUserClient();

  const { data, error } = await supabase
    .from("leads")
    .update(input)
    .eq("id", id)
    .select()
    .single();

  if (error) return { success: false, error: error.message };

  updateTag(CACHE_TAGS.LEADS);
  updateTag(CACHE_TAGS.LEAD_DETAILS(id));
  updateTag(CACHE_TAGS.LEAD_STATUS_COUNTS);
  revalidatePath("/leads");
  revalidatePath(`/leads/${id}`);

  return { success: true, data: data as Lead };
}

/**
 * Adds a phone number to a lead's `phones` array.
 * Checks for duplicates before inserting to prevent data inconsistency.
 *
 * @param leadId - Lead UUID
 * @param phone - Phone number string to add
 */
export async function addLeadPhone(
  leadId: string,
  phone: string
): Promise<ActionResult<Lead>> {
  const supabase = await getUserClient();

  const { data: lead } = await supabase
    .from("leads")
    .select("phones")
    .eq("id", leadId)
    .single();

  const currentPhones = lead?.phones || [];
  if (currentPhones.includes(phone)) {
    return { success: false, error: "Phone number already exists" };
  }

  const { data, error } = await supabase
    .from("leads")
    .update({ phones: [...currentPhones, phone] })
    .eq("id", leadId)
    .select()
    .single();

  if (error) return { success: false, error: error.message };

  updateTag(CACHE_TAGS.LEAD_DETAILS(leadId));
  revalidatePath(`/leads/${leadId}`);

  return { success: true, data: data as Lead };
}

/**
 * Bulk-assigns one or more leads to a CRE or Sales Executive.
 * Used from the lead table's multi-select action bar.
 *
 * @param leadIds - Array of lead UUIDs to update
 * @param userId - Target user's UUID
 * @param type - Whether to assign as 'cre' or 'sales' executive
 */
export async function bulkAssignLeads(
  leadIds: string[],
  userId: string,
  type: "cre" | "sales"
): Promise<ActionResult<boolean>> {
  const supabase = await getUserClient();

  const updateData =
    type === "cre"
      ? { cre_id: userId }
      : { sales_executive_id: userId };

  const { error } = await supabase
    .from("leads")
    .update(updateData)
    .in("id", leadIds);

  if (error) return { success: false, error: error.message };

  updateTag(CACHE_TAGS.LEADS);
  leadIds.forEach((id) => updateTag(CACHE_TAGS.LEAD_DETAILS(id)));
  revalidatePath("/leads");

  return { success: true, data: true };
}

/**
 * Adds a comment (optionally with image attachments) to a lead's activity feed.
 * The `comment_by` field is automatically set from the authenticated session.
 *
 * @param leadId - Lead UUID
 * @param comment - Comment text content
 * @param images - Optional array of Supabase storage public URLs
 */
export async function addLeadComment(
  leadId: string,
  comment: string,
  images: string[] = []
): Promise<ActionResult<LeadComment>> {
  const supabase = await getUserClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return { success: false, error: "Not authenticated" };

  const { data, error } = await supabase
    .from("lead_comments")
    .insert([
      {
        lead_id: leadId,
        comment_by: user.id,
        comment,
        images,
      },
    ])
    .select("*, user:users(id, name, profile_picture)")
    .single();

  if (error) return { success: false, error: error.message };

  updateTag(CACHE_TAGS.LEAD_DETAILS(leadId));
  revalidatePath(`/leads/${leadId}`);

  return { success: true, data: data as LeadComment };
}

/**
 * Records a payment against a lead. The `recorded_by` field is automatically
 * set from the authenticated session.
 *
 * Side-effect: After inserting, the computed finance view (`lead_finance_computed`)
 * will automatically reflect updated `totalPayment` and `totalDue` on next fetch —
 * no need to manually update the `finance` JSONB field.
 *
 * @param input - Payment data. `lead_id` is required.
 */
export async function addPayment(
  input: Partial<LeadPayment>
): Promise<ActionResult<LeadPayment>> {
  const supabase = await getUserClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();
  const paymentInput = { ...input, recorded_by: user?.id };

  const { data, error } = await supabase
    .from("lead_payments")
    .insert([paymentInput])
    .select("*, user:users(id, name, profile_picture)")
    .single();

  if (error) return { success: false, error: error.message };

  updateTag(CACHE_TAGS.LEAD_DETAILS(input.lead_id || ""));
  revalidatePath(`/leads/${input.lead_id}`);

  return { success: true, data: data as LeadPayment };
}

/**
 * Records an outgoing/incoming call against a lead.
 * The `recorded_by` field is auto-set from the authenticated session.
 *
 * @param input - Call log data. `lead_id` is required.
 */
export async function addCallLog(
  input: Partial<LeadCallLog>
): Promise<ActionResult<LeadCallLog>> {
  const supabase = await getUserClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();
  const logInput = { ...input, recorded_by: user?.id };

  const { data, error } = await supabase
    .from("lead_call_logs")
    .insert([logInput])
    .select("*, user:users(id, name, profile_picture)")
    .single();

  if (error) return { success: false, error: error.message };

  updateTag(CACHE_TAGS.LEAD_DETAILS(input.lead_id || ""));
  revalidatePath(`/leads/${input.lead_id}`);

  return { success: true, data: data as LeadCallLog };
}

/**
 * Updates the project status (pipeline stage) of a lead and logs a comment.
 * Setting `status: "Ongoing"` is the convention for project-phase updates.
 *
 * @param leadId - Lead UUID
 * @param status - High-level project status (e.g., "Measuring", "Production")
 * @param subStatus - Finer-grained sub-status (e.g., "Material Ordered")
 * @param comment - Required progress note for the lead activity feed
 */
export async function updateLeadProjectStatus(
  leadId: string,
  status: string,
  subStatus: string,
  comment: string
): Promise<ActionResult<boolean>> {
  const supabase = await getUserClient();

  const { error } = await supabase
    .from("leads")
    .update({
      status: "Ongoing",
      project_status: { status, subStatus },
    })
    .eq("id", leadId);

  if (error) return { success: false, error: error.message };

  await addLeadComment(leadId, comment);

  updateTag(CACHE_TAGS.LEAD_DETAILS(leadId));
  updateTag(CACHE_TAGS.LEADS);
  updateTag(CACHE_TAGS.LEAD_STATUS_COUNTS);
  revalidatePath(`/leads/${leadId}`);

  return { success: true, data: true };
}
/**
 * Bulk-creates multiple lead records in a single transaction.
 *
 * @param leads - Array of lead creation inputs
 */
export async function createLeadsBulk(
  leads: CreateLeadInput[]
): Promise<ActionResult<{ inserted: number; failed: number }>> {
  if (!leads.length) return { success: false, error: "No leads to import" };

  const supabase = await getUserClient();

  const { data, error } = await supabase
    .from("leads")
    .insert(leads)
    .select("id");

  if (error) return { success: false, error: error.message };

  updateTag(CACHE_TAGS.LEADS);
  updateTag(CACHE_TAGS.LEAD_STATUS_COUNTS);
  revalidatePath("/leads");

  return { 
    success: true, 
    data: { 
      inserted: data?.length || 0, 
      failed: leads.length - (data?.length || 0) 
    } 
  };
}

/**
 * Updates the status of a follow-up task.
 *
 * @param id - Follow-up UUID
 * @param status - New status (e.g., 'Complete', 'Pending')
 * @param leadId - Lead UUID for cache revalidation
 */
export async function updateFollowUpStatus(
  id: string,
  status: string,
  leadId: string
): Promise<ActionResult<boolean>> {
  const supabase = await getUserClient();

  const { error } = await supabase
    .from("lead_follow_ups")
    .update({ status })
    .eq("id", id);

  if (error) return { success: false, error: error.message };

  updateTag(CACHE_TAGS.LEAD_DETAILS(leadId));
  revalidatePath(`/leads/${leadId}`);

  return { success: true, data: true };
}

/**
 * Creates a new follow-up task for a lead.
 *
 * @param input - Follow-up data
 */
export async function createFollowUp(
  input: Partial<LeadFollowUp>
): Promise<ActionResult<LeadFollowUp>> {
  const supabase = await getUserClient();

  const { data, error } = await supabase
    .from("lead_follow_ups")
    .insert([input])
    .select()
    .single();

  if (error) return { success: false, error: error.message };

  updateTag(CACHE_TAGS.LEAD_DETAILS(input.lead_id || ""));
  revalidatePath(`/leads/${input.lead_id}`);

  return { success: true, data: data as LeadFollowUp };
}
